name: Build and Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # Or your default branch e.g., master, develop

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Specify your project's Node.js version. '18' is a good LTS.
          cache: 'npm'

      - name: Install dependencies
        run: npm ci # 'ci' is generally faster and more reliable for CI environments than 'install'
                   # Use 'npm install' if you don't have a package-lock.json

      - name: Build project
        run: npm run build # This should create the 'dist' folder as per your firebase.json

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0 # Official Firebase action
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}' # Automatically provided by GitHub
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_YOUR_PROJECT_NAME }}' # Create this secret in your repository
          channelId: live # Deploy to the live channel. For preview channels, you can use 'preview' or a custom ID.
          projectId: 'suyena-demo-app' # Replace with your Firebase Project ID
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels # Optional: enables preview channel features if you use them
